model_parameters:
  hidden_dims:
  - 32
  input_dim: 784
  output_dim: 10
training_parameters:
  batch_size: 8
  early_stopping: false
  epochs: 20
  lambda: 0.01
  learning_rate: 0.1
  momentum: 0.9
  patience: 10
