model_parameters:
  hidden_dims:
  - 16
  input_dim: 21
  output_dim: 1
training_parameters:
  batch_size: 32
  early_stopping: false
  epochs: 1000
  lambda: 0.1
  learning_rate: 0.001
  momentum: 0.9
  patience: 10
